### ISSUE TITLE
How to get the XNOCS map?

### ISSUE THREAD

**Issue by hiyyg** [drsrinathsridhar/xnocs#5]
Hi, very interesting work! Could you please share the code for generating the XNOCS map, so that we can compute the targets for other 3D models?

**Comment by drsrinathsridhar** [comment]
Thanks for your interest. Our code for X-NOCS map generation is all in Unity, specifically as a custom shader -- I am not sure if that code would be readable/useful. But our implementation closely follows Alec Jacobson's description of depth peeling:

http://www.alecjacobson.com/weblog/?p=4310
