### ISSUE TITLE
How to generate NOX map 

### ISSUE THREAD

**Issue by taeyeopl** [drsrinathsridhar/xnocs#6]
Thanks for sharing the good work. 
Can I ask how to generate **NOXRayTL_00.png and NOXRayTL_01.png**??
If you share some examples of data generation process, It would be appreciated. 

Thanks in advances.

**Comment by drsrinathsridhar** [comment]
We generated them using Unity using custom shaders. The shaders won't make much sense if you use them outside Unity. But our implementation closely follows:

https://blog.kitware.com/vtk-technical-highlight-dual-depth-peeling/
