### ISSUE TITLE
ModuleNotFoundError: No module named 'tk3dv.ptTools'

### ISSUE THREAD

**Issue by akaganeite** [drsrinathsridhar/xnocs#7]
Hi, i'am trying to implement your work on a server. But met the error ModuleNotFoundError: No module named 'tk3dv.ptTools' when running the code from tk3dv.ptTools import ptUtils.
I was wondering what may cause this error. I'm sure that tk3dv is added to the system path. 
Thanks.

**Comment by drsrinathsridhar** [comment]
I removed ptTools from the tk3dv library. But I have added it back for backwards compatibility. Please uninstall and reinstall tk3dv and try again. Let me know if it still doesn't work. Thanks.
