### ISSUE TITLE
Question about the ground truth of camera pose 

### ISSUE THREAD

**Issue by taeyeopl** [drsrinathsridhar/xnocs#8]
Thanks for sharing good work. 
I have some questions related to your work.

**Q1. Can you share your code of getting the ground truth of pose using NOCS and [1] ??**
I saw you only mentioned using [1] in the supplementary material and I wonder how to implement details.
I also wonder how many frames are used for getting the pose.

**Q2.As you mentioned in future work, Is there any method evaluating camera pose related NOCS??**
I would really appreciate it if you could share your work.

[1] Richard Hartley and Andrew Zisserman. Multiple view geometry in computer vision. Cambridge university press, 2003.

**Comment by drsrinathsridhar** [comment]
Hi there,

Here's some code that estimates camera pose from NOCS maps. That should answer both your questions.

https://github.com/drsrinathsridhar/tk3dv/blob/2076704fb07de062619432fce1bd3b3fe5b909cd/examples/visualizeNOCSMap.py#L115
